[package]
name = "service"                # The name of your Rust package (crate)
version = "0.1.1113"               # The version of your package
edition = "2021"                # The Rust edition (language features and idioms)

[dependencies]
actix-web = "4.4"               # Web framework for building HTTP servers
actix-cors = "0.6"              # CORS (Cross-Origin Resource Sharing) support for Actix Web
sentry = "0.32"                 # Error tracking and reporting to Sentry
sentry-actix = "0.32"           # Sentry integration for Actix Web
sentry-tracing = "0.32"         # Sentry integration with tracing spans
tokio = { version = "1.0", features = ["full"] } # Asynchronous runtime for Rust, with all features enabled
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono", "json", "bigdecimal"] }
# Async SQL toolkit, with support for Postgres, 
#many more UUIDs, chrono dates, JSON, and bigdecimal types are available
